export const exercises = [
  "pectoralis major",
  "biceps",
  "abdominals",
  "sartorius",
  "abductors",
  "trapezius",
  "deltoid",
  "latissimus dorsi",
  "serratus anterior",
  "external oblique",
  "brachioradialis",
  "finger extensors",
  "finger flexors",
  "quadriceps",
  "hamstrings",
  "gastrocnemius",
  "soleus",
  "infraspinatus",
  "teres major",
  "triceps",
  "gluteus medius",
  "gluteus maximus",
];
